# Generated by Django 5.0.6 on 2024-06-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="机构名称")),
                ("name", models.CharField(max_length=50, verbose_name="联系人")),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号")),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uname", models.CharField(max_length=50, verbose_name="用户名")),
                ("upass", models.TextField(max_length=256, verbose_name="密码")),
                (
                    "umoney",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="余额"
                    ),
                ),
                (
                    "uemail",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "uface",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="头像"
                    ),
                ),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "regdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册日期"),
                ),
                (
                    "regip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="注册IP"
                    ),
                ),
                (
                    "lastlogindate",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次登录日期"),
                ),
                (
                    "lastloginip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上次登录IP"
                    ),
                ),
                ("logintimes", models.IntegerField(default=0, verbose_name="登录次数")),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="会员组名称"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("page_list", models.TextField(verbose_name="页面权限")),
                ("cate_list", models.TextField(verbose_name="栏目权限")),
                (
                    "pagelever",
                    models.CharField(max_length=50, null=True, verbose_name="权限设置"),
                ),
                ("pagelock", models.SmallIntegerField(default=0, verbose_name="审核设置")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, null=True, verbose_name="老师姓名"),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="联系方式")),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="apis.institution",
                        verbose_name="机构",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="institution",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="apis.user",
                verbose_name="会员",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="users",
                to="apis.usergroup",
                verbose_name="会员组",
            ),
        ),
    ]
